[package]
name = "magika_ffi"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
magika = "1.0.0"
ort = { version = "2.0.0-rc.10", features = ["download-binaries"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"